apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: awssns-test
  name: awssns-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awssns-test
  strategy: {}
  template:
    metadata:
      labels:
        app: awssns-test
    spec:
      containers:
      - image: awssns_go
        name: awssns-test
        imagePullPolicy: Never
        env: 
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: awssns-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: awssns-secret
              key: aws_secret_access_key
        - name: AWS_REGION
          value: ap-northeast-1
        - name: SNS_TOPIC_ARN
          valueFrom:
            secretKeyRef:
              name: awssns-secret
              key: SNS_TOPIC_ARN